//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluOsNadRemote.App.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluOsNadRemote.App.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add player manually.
        /// </summary>
        internal static string AddPlayerHeader {
            get {
                return ResourceManager.GetString("AddPlayerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you failed to discover a player, you can manually enter an ip address or host here. Click &apos;Ping BluOS&apos; to see if a connection can be made. If some xml appears down here, then it succeeded. Then click &apos;Save&apos; to save the player..
        /// </summary>
        internal static string AddPlayerIntro {
            get {
                return ResourceManager.GetString("AddPlayerIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add player.
        /// </summary>
        internal static string AddPlayerTitle {
            get {
                return ResourceManager.GetString("AddPlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorites.
        /// </summary>
        internal static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio return channel.
        /// </summary>
        internal static string AudioReturnChannel {
            get {
                return ResourceManager.GetString("AudioReturnChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available services.
        /// </summary>
        internal static string AvailableServices {
            get {
                return ResourceManager.GetString("AvailableServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse album.
        /// </summary>
        internal static string BrowseAlbum {
            get {
                return ResourceManager.GetString("BrowseAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse artist.
        /// </summary>
        internal static string BrowseArtist {
            get {
                return ResourceManager.GetString("BrowseArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string Channels {
            get {
                return ResourceManager.GetString("Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec.
        /// </summary>
        internal static string Codec {
            get {
                return ResourceManager.GetString("Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connecting.
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect: {0}.
        /// </summary>
        internal static string CouldNotConnectResult {
            get {
                return ResourceManager.GetString("CouldNotConnectResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        internal static string DarkThemeLabel {
            get {
                return ResourceManager.GetString("DarkThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, default language is fine..
        /// </summary>
        internal static string DefaultLanguageLabel {
            get {
                return ResourceManager.GetString("DefaultLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, the default theme is fine..
        /// </summary>
        internal static string DefaultThemeLabel {
            get {
                return ResourceManager.GetString("DefaultThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirac.
        /// </summary>
        internal static string Dirac {
            get {
                return ResourceManager.GetString("Dirac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        internal static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover: No players found.
        /// </summary>
        internal static string DiscoverNoPlayersFound {
            get {
                return ResourceManager.GetString("DiscoverNoPlayersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover: Found {0} player(s) succesfully.
        /// </summary>
        internal static string DiscoverPlayersFound {
            get {
                return ResourceManager.GetString("DiscoverPlayersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display is dimmed.
        /// </summary>
        internal static string DisplayIsDimmed {
            get {
                return ResourceManager.GetString("DisplayIsDimmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en_US {
            get {
                return ResourceManager.GetString("en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End point.
        /// </summary>
        internal static string EndPoint {
            get {
                return ResourceManager.GetString("EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        internal static string LightThemeLabel {
            get {
                return ResourceManager.GetString("LightThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening mode.
        /// </summary>
        internal static string ListeningMode {
            get {
                return ResourceManager.GetString("ListeningMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string nl_NL {
            get {
                return ResourceManager.GetString("nl-NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve browsers.
        /// </summary>
        internal static string NoBrowsers {
            get {
                return ResourceManager.GetString("NoBrowsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect.
        /// </summary>
        internal static string NoConnect {
            get {
                return ResourceManager.GetString("NoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection could be made. Either try again by swiping down, or go to the Settings menu to setup a connection.
        /// </summary>
        internal static string NoConnectionDialogMessage {
            get {
                return ResourceManager.GetString("NoConnectionDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connections have been configured..
        /// </summary>
        internal static string NoConnections {
            get {
                return ResourceManager.GetString("NoConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connections have been configured. Would you like to proceed to the configuration screen and discover BluOs devices?.
        /// </summary>
        internal static string NoConnectionsDialogMessage {
            get {
                return ResourceManager.GetString("NoConnectionsDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve more.
        /// </summary>
        internal static string NoMore {
            get {
                return ResourceManager.GetString("NoMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve favorites.
        /// </summary>
        internal static string NoPresets {
            get {
                return ResourceManager.GetString("NoPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve playlist items.
        /// </summary>
        internal static string NoQueue {
            get {
                return ResourceManager.GetString("NoQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items.
        /// </summary>
        internal static string NumItems {
            get {
                return ResourceManager.GetString("NumItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than {0} items....
        /// </summary>
        internal static string NumMoreItems {
            get {
                return ResourceManager.GetString("NumMoreItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Presets.
        /// </summary>
        internal static string NumPresets {
            get {
                return ResourceManager.GetString("NumPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override language.
        /// </summary>
        internal static string OverrideLanguage {
            get {
                return ResourceManager.GetString("OverrideLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to use another language?.
        /// </summary>
        internal static string OverrideLanguageIntro {
            get {
                return ResourceManager.GetString("OverrideLanguageIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I rather have....
        /// </summary>
        internal static string OverrideLanguageOr {
            get {
                return ResourceManager.GetString("OverrideLanguageOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override theme.
        /// </summary>
        internal static string OverrideTheme {
            get {
                return ResourceManager.GetString("OverrideTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to use another theme?.
        /// </summary>
        internal static string OverrideThemeIntro {
            get {
                return ResourceManager.GetString("OverrideThemeIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I rather have the....
        /// </summary>
        internal static string OverrideThemeOr {
            get {
                return ResourceManager.GetString("OverrideThemeOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping BluOS.
        /// </summary>
        internal static string PingBluOS {
            get {
                return ResourceManager.GetString("PingBluOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping telnet.
        /// </summary>
        internal static string PingTelnet {
            get {
                return ResourceManager.GetString("PingTelnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playing.
        /// </summary>
        internal static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play similarstation.
        /// </summary>
        internal static string PlaySimilarstation {
            get {
                return ResourceManager.GetString("PlaySimilarstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play track station.
        /// </summary>
        internal static string PlayTrackstation {
            get {
                return ResourceManager.GetString("PlayTrackstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        internal static string Presets {
            get {
                return ResourceManager.GetString("Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from list.
        /// </summary>
        internal static string RemoveFromList {
            get {
                return ResourceManager.GetString("RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other language.
        /// </summary>
        internal static string SelectLanguageTitle {
            get {
                return ResourceManager.GetString("SelectLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More settings.
        /// </summary>
        internal static string SettingsMoreTitle {
            get {
                return ResourceManager.GetString("SettingsMoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stopped.
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to streaming.
        /// </summary>
        internal static string Streaming {
            get {
                return ResourceManager.GetString("Streaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub.
        /// </summary>
        internal static string Sub {
            get {
                return ResourceManager.GetString("Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surround.
        /// </summary>
        internal static string Surround {
            get {
                return ResourceManager.GetString("Surround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle power.
        /// </summary>
        internal static string TogglePower {
            get {
                return ResourceManager.GetString("TogglePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
