@base_url=http://192.168.107.241:11000
@service=Tidal

###GET FAVORITE ARTISTS
GET {{base_url}}/Artists?service={{service}}&category=FAVOURITES&sort=name
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET FAVORITE ALBUMS
GET {{base_url}}/Albums?service={{service}}&category=FAVOURITES&sort=name
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET FAVORITE RECENT ALBUMS
GET {{base_url}}/Albums?service={{service}}&category=FAVOURITES&inline=1&sort=recent
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET FAVORITE PLAYLISTS
GET {{base_url}}/Playlists?service={{service}}&category=FAVOURITES&sort=name
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET mymix PLAYLISTS
GET {{base_url}}/Playlists?service={{service}}&category=mymix
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET FAVORITE SONGS
GET {{base_url}}/Songs?service={{service}}&category=FAVOURITES&sort=name
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET service PLAYLISTS
GET {{base_url}}/Playlists?service={{service}}&sort=name
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET ui Home
GET {{base_url}}/ui/Home
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET ui Home
GET {{base_url}}/ui/Home?playnum=1
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET ui Sources
GET {{base_url}}/ui/Sources?playnum=1
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET Syncstatus
GET {{base_url}}/SyncStatus
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET Syncstatus
GET {{base_url}}/SyncStatus?etag=207&timeout=10
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET Status?etag=e939e85c9ea71e364762eef483be512a&timeout=100
GET {{base_url}}/Status
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET PLAYLIST
GET {{base_url}}/Playlist?start=1&end=1
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET BROWSE TRACKS VIA SONGS
GET {{base_url}}/Songs?service=Tidal&amp;browseIsFavouritesContext=1&amp;category=FAVOURITES
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET BROWSE TRACKS VIA BROWSE
GET {{base_url}}/Browse?key=%2FSongs%3Fservice%3DTidal%26amp%3BbrowseIsFavouritesContext%3D1%26amp%3Bcategory%3DFAVOURITES
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET CONTEXT MENU ALBUM VIA BROWSE
GET {{base_url}}/Browse?key=Tidal%3acontextMenu%2fAlbum%3falbumid%3d330930029%26isFavourite%3d1%26browseIsFavouritesContext%3d1
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET SONG INFO VIA BROWSE
GET {{base_url}}/Browse?key=%2FSongs%3Fservice%3DTidal%26songid%3D353990799

###GET CONTEXT MENU SONG VIA BROWSE
GET {{base_url}}/Browse?key=Tidal%3AcontextMenu%2FSong%3Ffilename%3DTidal%253A353990799%26amp%3Bsongid%3DTidal%253A353990799%26amp%3Btrackstationid%3DTidal%253Aradio%253Atrack%252F353990799

###GET SONG INFO
GET {{base_url}}/Songs?service=Tidal&songid=139297747
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET ALBUM INFO
GET {{base_url}}/Albums?service=Tidal&albumid=139297738
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET ARTIST INFO
GET {{base_url}}/Artists?service=Tidal&artistid=19325945
Accept-Language: nl-NL
User-Agent: Bluesound/4.0.3
x-sovi-schema-version: 34
x-sovi-ui-schema-version: 1
x-sovi-ui-autofill: 1

###GET BROWSE ROOT
GET {{base_url}}/Browse

###GET BROWSE TIDAL
GET {{base_url}}/Browse?key=Tidal%3A

###GET BROWSE TIDAL MY MUSIC
GET {{base_url}}/Browse?key=Tidal%3AmenuGroup%2F7

###GET BROWSE TIDAL MY MUSIC > ALBUMS
GET {{base_url}}/Browse?key=%2FAlbums%3Fservice%3DTidal%26amp%3BbrowseIsFavouritesContext%3D1%26amp%3Bcategory%3DFAVOURITES