//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluOsNadRemote.App.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluOsNadRemote.App.Resources.Localizations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you failed to discover a player, you can manually enter an ip address or host here. Click &apos;Ping BluOS&apos; to see if a connection can be made. If some xml appears down here, then it succeeded. Then click &apos;Save&apos; to save the player..
        /// </summary>
        public static string AddPlayerIntro {
            get {
                return ResourceManager.GetString("AddPlayerIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually add player.
        /// </summary>
        public static string AddPlayerTitle {
            get {
                return ResourceManager.GetString("AddPlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorites.
        /// </summary>
        public static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available services.
        /// </summary>
        public static string AvailableServices {
            get {
                return ResourceManager.GetString("AvailableServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse album.
        /// </summary>
        public static string BrowseAlbum {
            get {
                return ResourceManager.GetString("BrowseAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse artist.
        /// </summary>
        public static string BrowseArtist {
            get {
                return ResourceManager.GetString("BrowseArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect: {0}.
        /// </summary>
        public static string CouldNotConnectResult {
            get {
                return ResourceManager.GetString("CouldNotConnectResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover: No players found.
        /// </summary>
        public static string DiscoverNoPlayersFound {
            get {
                return ResourceManager.GetString("DiscoverNoPlayersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover: Found {0} player(s) succesfully.
        /// </summary>
        public static string DiscoverPlayersFound {
            get {
                return ResourceManager.GetString("DiscoverPlayersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve browsers.
        /// </summary>
        public static string NoBrowsers {
            get {
                return ResourceManager.GetString("NoBrowsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect.
        /// </summary>
        public static string NoConnect {
            get {
                return ResourceManager.GetString("NoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection.
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve more.
        /// </summary>
        public static string NoMore {
            get {
                return ResourceManager.GetString("NoMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve favorites.
        /// </summary>
        public static string NoPresets {
            get {
                return ResourceManager.GetString("NoPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve playlist items.
        /// </summary>
        public static string NoQueue {
            get {
                return ResourceManager.GetString("NoQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items.
        /// </summary>
        public static string NumItems {
            get {
                return ResourceManager.GetString("NumItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than {0} items....
        /// </summary>
        public static string NumMoreItems {
            get {
                return ResourceManager.GetString("NumMoreItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Presets.
        /// </summary>
        public static string NumPresets {
            get {
                return ResourceManager.GetString("NumPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play similarstation.
        /// </summary>
        public static string PlaySimilarstation {
            get {
                return ResourceManager.GetString("PlaySimilarstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play track station.
        /// </summary>
        public static string PlayTrackstation {
            get {
                return ResourceManager.GetString("PlayTrackstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from list.
        /// </summary>
        public static string RemoveFromList {
            get {
                return ResourceManager.GetString("RemoveFromList", resourceCulture);
            }
        }
    }
}
